### ISSUE TITLE
Change folder structure for more templates

### ISSUE THREAD

**Issue by FussballAndy** [JeyRunner/tuda-typst-templates#6]
# Edit structure for more templates

Given by the name and README of this repository I would assume that it is supposed to hold more than just a thesis template. Additionally I am currently working on the exercise template and would like all templates to be in a single repository. However the current structure is unfitting for that. Thus it would be a good idea to restructure the project.
I would like to use this issue thread to brainstorm a possible folder structure.

## My proposal

My first proposal would be something like the following:
```
tuda-typst-templates/
├─ fonts/
├─ logos/
├─ templates/
│  ├─ common/
│  ├─ tudapub/
│  │  ├─ example/
│  │  ├─ pub/
│  │  ├─ template/
│  │  ├─ lib.typ
│  │  ├─ typst.toml
├─ tests/
├─ ...
```

The idea is to have most of the code of each template in one single folder thus making the publishing to universe easier as only a limited set of files need to be copied. 
A small breakdown of each folder in a template:
- `example` source files for an example of the template. Ideally to be used as entrypoint for the template.
- `pub` files for publishing like an image of the template
- `template` the source of the template itself

Additionally the `fonts` and `logos` get extracted to the root to avoid copies of the same files. And the scripts do not need to be published to universe.

**Comment by JeyRunner** [comment]
Hi @FussballAndy,
nice to hear that you are working on adding an exercise template. You are correct, this repository was intended for multiple Tu Darmstadt related templates. 

Adapting the file structure to this is a good idea.  
Although I am not sure if the typst.toml can include things from the parent directory (`../common/`) (the same for the typst compiler itself, I did not test this yet).  In general, I am not sure how to handle importing the `common` folder from `tudapub` in this case. When I understand you correctly you want to copy the  `common` folder into the `tudapub/template` folder for publishing, which would work fine. But I think it is still important to have a working setup when developing the template (the import paths should also work without the copy of the `common` module). Maybe we can just create a symlink of `common` into every template folder.

Another possibility would be to make `common` into a separate package which is imported in all templates.
But I think when including the parent folders works, your proposal is better/simpler.

Maybe some general parts for the layout setup in the current `tudapub.typ` can also be moved to helper functions in `common` to make them reusable for the exercise template (like page margins, spacing, ...).

**Comment by FussballAndy** [comment]
Whilst I think importing from a parent directory works  as long as it is in the project root directory, I still think that we should not rely on that as we would then need to change the import paths everytime we publish to universe. I am also not sure if creating a package for the common files would be a good resolution, as it would only be a very niche package and I am not sure if universe wants that. 
I really like the idea with symlinks as thus we can utilize a common folder but also keep a proper development environment and do not need to adapt the imports everytime we publish (although to be fair we probably wont publish frequently so this would only need be done a handful of times). Though I am not entirely sure how well symlinks work with Git and different platfoms.

**Comment by JeyRunner** [comment]
@FussballAndy I refactored the repo to the following structure following the symlink approach:
```
.
├── assets
│   ├── fonts
│   └── logos
├── common
├── scripts
├── templates
│   ├── tudaexercise
│   │   ├── preview
│   │   └── template
│   │       └── common -> ../../../common
│   └── tudapub
│       ├── preview
│       └── template
│           └── common -> ../../../common
├── templates_examples
│   ├── tudaexercise
│   │   ├── fonts -> ../../assets/fonts
│   │   └── logos -> ../../assets/logos
│   └── tudapub
│       ├── fonts -> ../../assets/fonts
│       └── logos -> ../../assets/logos
├── tests
```

You can test it with in branch https://github.com/JeyRunner/tuda-typst-templates/tree/6-change-folder-structure-for-more-templates (#7) .
I also adapted the `scripts/publish.py` to work for multiple templates. When you now invoke this script with `python scripts/publish.py --local` you get the following two separate templates in your local typst package folder (`~/.local/share/typst/packages/local/`):
```
.
├── athena-tu-darmstadt-exercise
│   └── 0.1.0
│       ├── example
│       │   ├── fonts
│       │   ├── logos
│       │   ├──  ...
│       ├── LICENSE
│       ├── README.md
│       ├── template
│       │   ├── common
│       │   │   ├── ...
│       │   ├── lib.typ
│       │   └── tudaexercise.typ
│       └── typst.toml
└── athena-tu-darmstadt-thesis
    └── 0.1.0
        ├── example
        │   ├── fonts
        │   ├── logos
        │   ├── ...
        ├── LICENSE
        ├── preview
        │   └── ...
        ├── README.md
        ├── template
        │   ├── common
        │   │   ├── ...
        │   ├── lib.typ
        │   └── tudapub.typ
        └── typst.toml
```

**Comment by FussballAndy** [comment]
Hi, thank you very much, I'll take a final look at it tomorrow. 
Just one thing I realized is that a few files within `common` seem to be rather specific to the thesis template. Should these files really be in `common`? If they are more general files we should perhaps rename them and their contents to fit a more general design else we should probably move them in the `tudapub` template folder.

**Comment by JeyRunner** [comment]
Yes, currently the common lib is a bit cluttered. It is kind of on purpose, since some functionality of the thesis template may be reusable. When the exercise template is done, I think we can move some parts that are really only used by the thesis template out of the common lib. But for now I would keep them there (there is no disadvantage to this since the lib.typ of each template limits what is exposed to the user anyway).

**Comment by JeyRunner** [comment]
I also added a first starting point for the exercise template (basically an adapted version of the thesis template). 
![image](https://github.com/user-attachments/assets/d9c50c62-3597-46c9-81d5-808e63aa38bc)

**Comment by FussballAndy** [comment]
Jepp then we'll just keep them in the `common` folder. Also appreciate the template and the setup for a reference.
I've now taken one final look and everything looks good. I also checked and the symlinks also work on Windows with certain options (see (this)[https://stackoverflow.com/a/59761201/15192950] SO post). So that will also be fine. Thus, unless you want to add something more to your current PR, I'd be more than happy with the current state of changes.

**Comment by JeyRunner** [comment]
Perfect, I merged the new structure.
Just open a pull request for your future changes to the exercise template. Feel free to add/adapt stuff in the common lib. Just keep in mind that some parts of the common lib are also used in the thesis template, so when you change something check if it is also used by the thesis template, and if that is the case better test that the thesis template still works/looks the same. But currently just very simple functions are also used by the thesis template (colours, ...). 

At some point would be best to have automatic tests that compare the render of the current templates with a reference.
